on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:
  push:
    branches:
      - main
# merge upstream/master on these repos of my own: mineflayer (use matrix of repos)
jobs:
  update-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["mineflayer"]
    steps:
      - run: git clone "https://github.com/${{ github.repository_owner }}/${{ matrix.repo }}" "${{ matrix.repo }}"
      - name: Add upstream remote
        working-directory: ${{ matrix.repo }}
        run: |
          original_repo_url=$(curl -s https://api.github.com/repos/${{ github.repository_owner }}/${{ matrix.repo }} | jq -r .parent.clone_url)
          git remote add upstream $original_repo_url
      - name: Merge upstream/master
        working-directory: ${{ matrix.repo }}
        run: |
          git fetch upstream
          git merge upstream/master
      # if there are merge conflicts error out
      - name: Check for merge conflicts
        working-directory: ${{ matrix.repo }}
        run: |
          git diff --check
      - name: Push changes
        working-directory: ${{ matrix.repo }}
        run: |
          git push
